variable "env" {}
variable "public_vpc_cidr" {}
variable "private_vpc_cidr" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "AZS" {}
variable "default_vpc" {}
variable "default_vpc_cidr" {}
variable "private_hosted_zone_id" {}
variable "public_hosted_zone_id" {}