variable "env" {}
variable "spot_count" {}
variable "od_count" {}
variable "instance_type" {}
variable "component" {}
variable "port" {}
variable "is_public" {}
variable "priority" {}
variable "APP_VERSION" {}
